### ISSUE TITLE
Move away from XMSBT

### ISSUE THREAD

**Issue by anna-is-cute** [linktlh/Linkle-Dialog-Fixes#11]
XMSBT has a few issues:

- It's XML, which isn't the worst thing, but it sure is verbose.
- It mixes CRLF and LF line endings (only on Windows).
- It mixes binary data and text.
- It has no CLI interface for importing/exporting.
- It's slow to batch import/export.
- It's UTF-16, which is an overall pain to use.

I have come up with a new format called [MSYT](https://github.com/jkcclemens/msyt) (see very end for naming decisions).

- It's YAML, which is concise (although my emitter could be more concise).
- It does not mix CRLF and LF.
- It does not mix binary data and text. In fact, it keeps them explicitly separate.
- It has a CLI interface for importing/exporting and can do it in batch.
- It's very fast. It can batch import/export every file in the repo in *under 1 second*.
- It's UTF-8, which is the standard expected.

XMSBT has one pro, though: it has a GUI interface for import/export. MSYT only operates on the command line. In the future, I can attempt to make a GUI for MSYT, but I'm notably bad at making those.

I've converted all the MSBT files to MSYT [on my own fork](https://github.com/jkcclemens/Linkle-Dialog-Fixes/tree/msyt/). Feel free to browse and see what MSYT looks like. I'll drop a small file below.

I also have binaries for Windows and Linux for the importer/exporter if anyone wants to try it out.

I suggest we move the repo away from XMSBT and move towards MSYT due to the cons of XMSBT listed above. ~~However, the importer/exporter for MSYT is very fragile at this moment - I need to implement better error handling and UX for it~~ The importer/exporter for MSYT has been updated and is now workable, but I want to put this issue up so any concerns or questions can be addressed.

---

**EventFlowMsg/Npc_DeathMt001.msyt**

```yaml
---
entries:
  Talk00:
    - utf16_bytes:
        - 14
        - 3
        - 1
        - 2
        - 11
    - ascii: "I hope that someday I can capture the\nsame majesty that Ozunda does in my\nown work."
    - utf16_bytes:
        - 0
```

---

Reason for MSYT name: basically, XMSBT means XML MSBT. I brainstormed with @polarbunny that MSBT most likely means "Message Standard Binary Table" or something to that effect. So MSYT just means Message Standard YAML Table.

**Comment by anna-is-cute** [comment]
A problem I see currently, which could be fixed, is that the text fields supported are only ASCII. While this works well for English text, other languages would be hurt by this.

I could change `ascii` to `text`, but then I would have to also change the logic that splits the sections apart to check for unicode characters that are considered text (which is *notoriously* difficult).

**Comment by polarbunny** [comment]
> 
> 
> A problem I see currently, which could be fixed, is that the text fields supported are only ASCII. While this works well for English text, other languages would be hurt by this.
> 
> I could change `ascii` to `text`, but then I would have to also change the logic that splits the sections apart to check for unicode characters that are considered text (which is _notoriously_ difficult).

That is definitely an issue. But not vital at the moment I think?

**Comment by anna-is-cute** [comment]
We could come back to it later. I should change the `ascii` fields to `text` either way, so that when the time comes, it's not a breaking change that requires all the files to be updated.

**Comment by anna-is-cute** [comment]
Okay, well, like a total mad lad I went and did it. This presents an interesting issue, though.

```yaml
  TerrorFire:
    - utf16_bytes:
        - 14
        - 4   
        - 1
        - 2
    - text: 촔Ack!
    - utf16_bytes:
        - 0
```

I'm not sure if that character is part of the control bytes (`utf16_bytes` sections) and it's just a coincidence it happens to be a valid text character. I strongly suspect that, but there's no real way for me to tell without also reverse-engineering the control characters... which would be really cool but a lot of work.

Edit: Also, the control characters are likely BotW specific, which is annoying for making a tool that works on more that just one game.

Edit 2: For the time being, msyt should *not* be used for *both* Wii U and Switch. Each should have their own MSYT files. I have to 100% reverse engineer the BotW control sequences before you can use one MSYT file for both versions. Thanks, developers.

**Comment by polarbunny** [comment]
Lock and close? Or should we wait until msyt is "100%" complete?

**Comment by linktlh** [comment]
Yep already have msyt on the master branch. (Still need to setup file structure and feedback on personal preferences would be great, but I’ll close this issue for now but I won’t lock it)
